syntax = rule*
rule = name '=' options-list '\n'
options-list = gen+ ('|' gen+)*
gen = (range | str-lit | name | '(' options-list ')' ) mod?
range = '[' . '-' . ']'
str-lit = '\'' . '\'' | '\"' . '\"'
name = [a-z] ([a-z] | [0-9] | '-')*
mod = '*' | '+' | '?'